/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTRPCSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTRPCSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractRPCServer : public jsonrpc::AbstractServer<AbstractRPCServer>
{
    public:
        AbstractRPCServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<AbstractRPCServer>(conn, type)
        {
            this->bindAndAddNotification(jsonrpc::Procedure("sayHello", jsonrpc::PARAMS_BY_NAME,  NULL), &AbstractRPCServer::sayHelloI);
        }

        inline virtual void sayHelloI(const Json::Value &request)
        {
            (void)request;
            this->sayHello();
        }
        virtual void sayHello() = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTRPCSERVER_H_
